### ISSUE TITLE
macOS cannot verify that this app is free from malware

### ISSUE THREAD

**Issue by fandm** [FleXoft/Xerox-Phaser-3140-3155-macOS-Catalina-Big-Sur-Monterey-driver#1]
Hi,
It displays the following warnings every time I'm trying to print something. Please see the attached screenshots.
macOS version is Sonoma 14.4.1 (23E224).
Thanks!

<img width="260" alt="Screenshot 2024-09-17 at 09 40 32" src="https://github.com/user-attachments/assets/1796e063-3f32-4913-993d-947faf034e48">
<img width="261" alt="Screenshot 2024-09-17 at 09 40 49" src="https://github.com/user-attachments/assets/89478512-d848-4c6d-872e-00bd92fa8e20">
<img width="259" alt="Screenshot 2024-09-17 at 09 41 02" src="https://github.com/user-attachments/assets/fa802db5-a0d6-432f-bae4-aa2409337221">
<img width="260" alt="Screenshot 2024-09-17 at 09 41 15" src="https://github.com/user-attachments/assets/fc7fe1c7-9b5b-4660-b0b4-debb2cdc383c">
<img width="263" alt="Screenshot 2024-09-17 at 09 41 33" src="https://github.com/user-attachments/assets/41d12b34-2bdc-4964-ac9f-ade3d27df5c9">

**Comment by fandm** [comment]
Never mind.
Fixed with
`sudo spctl --master-disable`

**Comment by fandm** [comment]
Resolved.

**Comment by FleXoft** [comment]
Yes, in the newer operating systems, running an unsigned code is getting tighter, but in my opinion turning off the gatekeeper is not a good idea. 
Try this command as a work around if you have installed Xcode cmd line utils: 

`codesign --force --deep --sign - <programname/directory>`

or walk through all the files manually via Finder / right click and open which also will override and let them run...
