### ISSUE TITLE
copy command not work on mac os 15.1.1

### ISSUE THREAD

**Issue by cuthbertnogood** [FleXoft/Xerox-Phaser-3140-3155-macOS-Catalina-Big-Sur-Monterey-driver#2]
I fixed it in the following way

mkdir -p /Library/Printers/Xerox/Phaser_3140_3155
mkdir -p /Library/Printers/PPDs/Contents/Resources/
mkdir -p /private/etc/cups/ppd/

cp -R Library/Printers/Xerox/Phaser_3140_3155/* /Library/Printers/Xerox/Phaser_3140_3155

cp -R "Library/Printers/PPDs/Contents/Resources/Xerox Phaser 3140 and 3155.gz"  
"/Library/Printers/PPDs/Contents/Resources/Xerox Phaser 3140 and 3155.gz"

cp -R private/etc/cups/ppd/Xerox_Phaser_3140_and_3155.ppd  /private/etc/cups/ppd/Xerox_Phaser_3140_and_3155.ppd

**Comment by FleXoft** [comment]
Thnx. 👍
